services:
    ongr_xt_commerce.sync.data_sync.source:
        class: %ongr_connections.sync.data_sync.source.class%
        arguments:
            - @ongr_connections.sync.diff_provider.binlog_diff_provider
        tags:
            - { name: kernel.event_listener, event: ongr.pipeline.data_sync.default.source, method: onSource }

    ongr_xt_commerce.sync.data_sync.consume:
        class: %ongr_connections.sync.data_sync.consume.class%
        arguments:
            - @ongr_connections.sync.extractor.doctrine_extractor
        tags:
            - { name: kernel.event_listener, event: ongr.pipeline.data_sync.default.consume, method: onConsume }

    # RELATIONS FOR CATEGORIES
    ongr_xt_commerce.sql_relations.category.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_categories, D, OLD.categories_id, 1, category]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_xt_commerce.sql_relations.product.join.category.delete ] ]

    ongr_xt_commerce.sql_relations.category.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_categories, U, NEW.categories_id, 1, category]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_xt_commerce.sql_relations.product.join.category ] ]

    ongr_xt_commerce.sql_relations.product.join.category:
        class: %ongr_connections.extractor.join_relation.class%
        arguments: [xt_products_to_categories AS ptoc, ptoc.products_id, ptoc.categories_id=NEW.categories_id, product, U, 1]

    ongr_xt_commerce.sql_relations.product.join.category.delete:
        class: %ongr_connections.extractor.join_relation.class%
        arguments: [xt_products_to_categories AS ptoc, ptoc.products_id, ptoc.categories_id=OLD.categories_id, product, U, 1]

    ongr_xt_commerce.sql_relations.category.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_categories, C, NEW.categories_id, 1, category]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.category_description.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_categories_description, U, NEW.categories_id, 1, category]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_xt_commerce.sql_relations.product.join.category ] ]

    # RELATIONS FOR CONTENT
    ongr_xt_commerce.sql_relations.content.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_content_elements, D, OLD.content_id, 1, content]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.content.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_content_elements, U, OLD.content_id, 1, content]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.content.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_content_elements, C, NEW.content_id, 1, content]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    # RELATIONS FOR IMAGES
    ongr_xt_commerce.sql_relations.image.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_media, D, OLD.id, 1, image]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_xt_commerce.sql_relations.product.join.image ] ]

    ongr_xt_commerce.sql_relations.image.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_media, U, OLD.id, 1, image]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_xt_commerce.sql_relations.product.join.image ] ]

    ongr_xt_commerce.sql_relations.image.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_media, C, NEW.id, 1, image]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.image_description.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_media_description, U, OLD.id, 1, image]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_xt_commerce.sql_relations.product.join.image ] ]

    ongr_xt_commerce.sql_relations.product.join.image:
        class: %ongr_connections.extractor.join_relation.class%
        arguments: [xt_media_link AS mlink, mlink.link_id, mlink.m_id = OLD.id, product, U, 1]


    # RELATIONS FOR PRODUCTS
    ongr_xt_commerce.sql_relations.product.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_products, D, OLD.products_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.product.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_products, U, OLD.products_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.product.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_products, C, NEW.id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.product_category.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_products_to_categories, U, OLD.products_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.product_description.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_products_description, U, OLD.products_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.product_images.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_media_link, U, OLD.link_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    # Updates for seo urls. Possibility for false-positives.
    ongr_xt_commerce.sql_relations.product_seo.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_seo_url, U, OLD.link_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_xt_commerce.sql_relations.content_seo.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [xt_seo_url, U, OLD.link_id, 1, content]
        tags:
            - { name: ongr_connections.extraction_descriptor }
