language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/,Resources/public/ ./

